---
  - name: config_kvm_network | Defining virtual networks
    virt_net:
      command: "define"
      name: "{{ item['name'] }}"
      xml: "{{ lookup('template', 'kvm-network.xml.j2') }}"
    register: "kvm_bridges_defined"
    become: true
    with_items: '{{ kvm_virtual_networks }}'

  - name: config_kvm_network | Setting state of virtual networks
    virt_net:
      state: "{{ item['state'] }}"
      name: "{{ item['name'] }}"
    become: true
    with_items: '{{ kvm_virtual_networks }}'
    when: item['state'] is defined

  - name: config_kvm_network | Setting virtual networks to autostart
    virt_net:
      autostart: yes
      name: "{{ item['name'] }}"
    become: true
    with_items: '{{ kvm_virtual_networks }}'
    when: >
          (item['autostart'] is defined and
            item['autostart']) and
            (item['state'] is defined and
              item['state'] == "active")

  - name: config_kvm_network | Setting virtual networks to not autostart
    virt_net:
      autostart: no
      name: "{{ item['name'] }}"
    become: true
    with_items: '{{ kvm_virtual_networks }}'
    when: >
          item['autostart'] is defined and
          not item['autostart']

  - name: congfig_kvm_network | Remove default virtual network
    virt_net:
      state: "absent"
      command: "undefine"
      name: "default"
    become: true
    when: kvm_delete_default_network

  
