
  - name: main | Setting libvirt service name (CentOS)
    set_fact:
      kvm_service_name: 'libvirtd'
    when: ansible_distribution == "CentOS"
  - name: main | Setting libvirt service name (Ubuntu)
    set_fact:
      kvm_service_name: 'libvirt-bin'
    when: ansible_distribution == "Ubuntu"

  - include: install_kvm_centos7.yml
    when: ansible_os_family == "RedHat" and ansible_distribution == "CentOS" and ansible_distribution_major_version|int == 7

  - include: install_kvm_ubuntu.yml
    when: ansible_os_family == "Debian" and ansible_distribution == "Ubuntu"

  - include: config_users.yml
    when: kvm_config_users

  - include: config_kvm.yml

  - include: config_kvm_network.yml
    when: kvm_create_network

  - name: main | Configuring ssh to allow root logins
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      regexp: "^PermitRootLogin"
      line: "PermitRootLogin yes"
    become: true
    when: ssh_config_allow_root
